//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func (in *CredentialsSecretRef) DeepCopyInto(out *CredentialsSecretRef) {
	*out = *in
}

func (in *CredentialsSecretRef) DeepCopy() *CredentialsSecretRef {
	if in == nil {
		return nil
	}
	out := new(CredentialsSecretRef)
	in.DeepCopyInto(out)
	return out
}

func (in *MQTTBridge) DeepCopyInto(out *MQTTBridge) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *MQTTBridge) DeepCopy() *MQTTBridge {
	if in == nil {
		return nil
	}
	out := new(MQTTBridge)
	in.DeepCopyInto(out)
	return out
}

func (in *MQTTBridge) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *MQTTBridgeList) DeepCopyInto(out *MQTTBridgeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTBridge, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *MQTTBridgeList) DeepCopy() *MQTTBridgeList {
	if in == nil {
		return nil
	}
	out := new(MQTTBridgeList)
	in.DeepCopyInto(out)
	return out
}

func (in *MQTTBridgeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *MQTTBridgeSpec) DeepCopyInto(out *MQTTBridgeSpec) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(CredentialsSecretRef)
		**out = **in
	}
	if in.Topics != nil {
		in, out := &in.Topics, &out.Topics
		*out = make([]TopicConfig, len(*in))
		copy(*out, *in)
	}
}

func (in *MQTTBridgeSpec) DeepCopy() *MQTTBridgeSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTBridgeSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *MQTTBridgeStatus) DeepCopyInto(out *MQTTBridgeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastConnectedTime != nil {
		in, out := &in.LastConnectedTime, &out.LastConnectedTime
		*out = (*in).DeepCopy()
	}
	if in.LastDisconnectedTime != nil {
		in, out := &in.LastDisconnectedTime, &out.LastDisconnectedTime
		*out = (*in).DeepCopy()
	}
}

func (in *MQTTBridgeStatus) DeepCopy() *MQTTBridgeStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTBridgeStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *MQTTDevice) DeepCopyInto(out *MQTTDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *MQTTDevice) DeepCopy() *MQTTDevice {
	if in == nil {
		return nil
	}
	out := new(MQTTDevice)
	in.DeepCopyInto(out)
	return out
}

func (in *MQTTDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *MQTTDeviceList) DeepCopyInto(out *MQTTDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MQTTDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *MQTTDeviceList) DeepCopy() *MQTTDeviceList {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceList)
	in.DeepCopyInto(out)
	return out
}

func (in *MQTTDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *MQTTDeviceSpec) DeepCopyInto(out *MQTTDeviceSpec) {
	*out = *in
	out.BridgeRef = in.BridgeRef
	if in.TypeRef != nil {
		in, out := &in.TypeRef, &out.TypeRef
		*out = new(TypeRef)
		**out = **in
	}
}

func (in *MQTTDeviceSpec) DeepCopy() *MQTTDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *MQTTDeviceStatus) DeepCopyInto(out *MQTTDeviceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSeenTime != nil {
		in, out := &in.LastSeenTime, &out.LastSeenTime
		*out = (*in).DeepCopy()
	}
	if in.LastUpdatedTime != nil {
		in, out := &in.LastUpdatedTime, &out.LastUpdatedTime
		*out = (*in).DeepCopy()
	}
	if in.Reachable != nil {
		in, out := &in.Reachable, &out.Reachable
		*out = new(bool)
		**out = **in
	}
	if in.BatteryPct != nil {
		in, out := &in.BatteryPct, &out.BatteryPct
		*out = new(int32)
		**out = **in
	}
	if in.LinkQuality != nil {
		in, out := &in.LinkQuality, &out.LinkQuality
		*out = new(int32)
		**out = **in
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

func (in *MQTTDeviceStatus) DeepCopy() *MQTTDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(MQTTDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ObjectRef) DeepCopyInto(out *ObjectRef) {
	*out = *in
}

func (in *ObjectRef) DeepCopy() *ObjectRef {
	if in == nil {
		return nil
	}
	out := new(ObjectRef)
	in.DeepCopyInto(out)
	return out
}

func (in *TopicConfig) DeepCopyInto(out *TopicConfig) {
	*out = *in
}

func (in *TopicConfig) DeepCopy() *TopicConfig {
	if in == nil {
		return nil
	}
	out := new(TopicConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *TypeRef) DeepCopyInto(out *TypeRef) {
	*out = *in
}

func (in *TypeRef) DeepCopy() *TypeRef {
	if in == nil {
		return nil
	}
	out := new(TypeRef)
	in.DeepCopyInto(out)
	return out
}
